"""Fixin

Revision ID: 3ac41ce22b37
Revises: 7a35d48aa900
Create Date: 2023-10-23 13:24:49.753843

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3ac41ce22b37'
down_revision = '7a35d48aa900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_past_game_date'), ['date'], unique=False)

    with op.batch_alter_table('songfull', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'past_game', ['date_played'], ['date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songfull', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('past_game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_past_game_date'))

    # ### end Alembic commands ###
