"""Got rid of archive table, moved to Songfull

Revision ID: 7a35d48aa900
Revises: 6ac20db6fea2
Create Date: 2023-10-23 00:04:53.848515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a35d48aa900'
down_revision = '6ac20db6fea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_game', schema=None) as batch_op:
        batch_op.drop_column('song_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_id', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
