"""guess columns

Revision ID: 83f946d8f775
Revises: 0e0bdb489286
Create Date: 2023-10-30 21:17:02.409014

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '83f946d8f775'
down_revision = '0e0bdb489286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guess_1', sa.String(150), nullable=True))
        batch_op.add_column(sa.Column('guess_2', sa.String(150), nullable=True))
        batch_op.add_column(sa.Column('guess_3', sa.String(150), nullable=True))
        batch_op.add_column(sa.Column('guess_4', sa.String(150), nullable=True))
        batch_op.add_column(sa.Column('guess_5', sa.String(150), nullable=True))
        batch_op.add_column(sa.Column('guess_6', sa.String(150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_game', schema=None) as batch_op:
        batch_op.drop_column('guess_6')
        batch_op.drop_column('guess_5')
        batch_op.drop_column('guess_4')
        batch_op.drop_column('guess_3')
        batch_op.drop_column('guess_2')
        batch_op.drop_column('guess_1')

    # ### end Alembic commands ###
