"""Expanded Archive

Revision ID: d958e161a4d5
Revises: 74e8b1b52a95
Create Date: 2023-10-21 20:12:13.809506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd958e161a4d5'
down_revision = '74e8b1b52a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('release', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('current', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_column('current')
        batch_op.drop_column('release')
        batch_op.drop_column('album')

    # ### end Alembic commands ###
