"""Changed current column type, + add to archive

Revision ID: d98f3d17cee4
Revises: a9df5d2910c2
Create Date: 2023-10-22 02:17:07.172297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd98f3d17cee4'
down_revision = 'a9df5d2910c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current', sa.SmallInteger(), nullable=False))

    op.drop_constraint('artgen_sql_ibfk_1', 'artgen_sql', type_='foreignkey')

    with op.batch_alter_table('genre_sql', schema=None) as batch_op:
        batch_op.alter_column('genre',
                              existing_type=mysql.VARCHAR(length=255),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=False)
        batch_op.alter_column('sim_genres',
                              existing_type=mysql.VARCHAR(length=255),
                              type_=sa.TEXT(),
                              existing_nullable=True)
        batch_op.alter_column('sim_weights',
                              existing_type=mysql.VARCHAR(length=255),
                              type_=sa.TEXT(),
                              existing_nullable=True)
        batch_op.alter_column('opp_genres',
                              existing_type=mysql.VARCHAR(length=255),
                              type_=sa.TEXT(),
                              existing_nullable=True)
        batch_op.alter_column('opp_weights',
                              existing_type=mysql.VARCHAR(length=255),
                              type_=sa.TEXT(),
                              existing_nullable=True)
        batch_op.alter_column('spotify_url',
                              existing_type=mysql.VARCHAR(length=255),
                              type_=sa.TEXT(),
                              existing_nullable=True)
        batch_op.alter_column('color_hex',
                              existing_type=mysql.VARCHAR(length=255),
                              type_=sa.TEXT(),
                              existing_nullable=True)
        batch_op.alter_column('color_rgb',
                              existing_type=mysql.VARCHAR(length=255),
                              type_=sa.TEXT(),
                              existing_nullable=True)
        batch_op.alter_column('closest_stat_genres',
                              existing_type=mysql.VARCHAR(length=255),
                              type_=sa.TEXT(),
                              existing_nullable=True)

    with op.batch_alter_table('songfull', schema=None) as batch_op:
        batch_op.alter_column('current',
                              existing_type=mysql.TINYINT(display_width=1),
                              type_=sa.SmallInteger(),
                              existing_nullable=True)

    op.create_foreign_key('artgen_sql_ibfk_1', 'artgen_sql', 'genre_sql', ['genre_name'], ['genre'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songfull', schema=None) as batch_op:
        batch_op.alter_column('current',
                              existing_type=sa.SmallInteger(),
                              type_=mysql.TINYINT(display_width=1),
                              existing_nullable=True)

    with op.batch_alter_table('genre_sql', schema=None) as batch_op:
        batch_op.alter_column('closest_stat_genres',
                              existing_type=sa.TEXT(),
                              type_=mysql.VARCHAR(length=255),
                              existing_nullable=True)
        batch_op.alter_column('color_rgb',
                              existing_type=sa.TEXT(),
                              type_=mysql.VARCHAR(length=255),
                              existing_nullable=True)
        batch_op.alter_column('color_hex',
                              existing_type=sa.TEXT(),
                              type_=mysql.VARCHAR(length=255),
                              existing_nullable=True)
        batch_op.alter_column('spotify_url',
                              existing_type=sa.TEXT(),
                              type_=mysql.VARCHAR(length=255),
                              existing_nullable=True)
        batch_op.alter_column('opp_weights',
                              existing_type=sa.TEXT(),
                              type_=mysql.VARCHAR(length=255),
                              existing_nullable=True)
        batch_op.alter_column('opp_genres',
                              existing_type=sa.TEXT(),
                              type_=mysql.VARCHAR(length=255),
                              existing_nullable=True)
        batch_op.alter_column('sim_weights',
                              existing_type=sa.TEXT(),
                              type_=mysql.VARCHAR(length=255),
                              existing_nullable=True)
        batch_op.alter_column('sim_genres',
                              existing_type=sa.TEXT(),
                              type_=mysql.VARCHAR(length=255),
                              existing_nullable=True)
        batch_op.alter_column('genre',
                              existing_type=sa.VARCHAR(length=50),
                              type_=mysql.VARCHAR(length=255),
                              existing_nullable=False)

    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_column('current')

    # ### end Alembic commands ###
