"""removed songfull, changed key db to blob

Revision ID: f3bbc107a7aa
Revises: 2ea82ee9ac53
Create Date: 2023-11-30 11:55:17.226931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3bbc107a7aa'
down_revision = '2ea82ee9ac53'
branch_labels = None
depends_on = None


def upgrade():
    # Drop foreign key constraints before dropping the tables they reference
    # op.drop_constraint('past_game_ibfk_1', 'past_game', type_='foreignkey')
    # op.drop_constraint('current_game_ibfk_1', 'current_game', type_='foreignkey')
    # with op.batch_alter_table('archive', schema=None) as batch_op:
    # batch_op.drop_index('ix_archive_date_played')

    op.drop_table('archive')
    op.drop_table('current_game')
    with op.batch_alter_table('past_game', schema=None) as batch_op:
        batch_op.drop_index('ix_past_game_date')

    op.drop_table('past_game')
    with op.batch_alter_table('songfull', schema=None) as batch_op:
        batch_op.drop_index('ix_songfull_genre')

    op.drop_table('songfull')

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('api_key_encrypted',
                              existing_type=mysql.VARCHAR(length=255),
                              type_=sa.BLOB(),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('api_key_encrypted',
                              existing_type=sa.BLOB(),
                              type_=mysql.VARCHAR(length=255),
                              existing_nullable=True)

    op.create_table('songfull',
                    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
                    sa.Column('artist', mysql.VARCHAR(length=150), nullable=False),
                    sa.Column('id', mysql.VARCHAR(length=150), nullable=False),
                    sa.Column('artist_id', mysql.VARCHAR(length=150), nullable=False),
                    sa.Column('image_url', mysql.VARCHAR(length=250), nullable=True),
                    sa.Column('external_url', mysql.VARCHAR(length=250), nullable=True),
                    sa.Column('spotify_preview_url', mysql.VARCHAR(length=250), nullable=False),
                    sa.Column('popularity', mysql.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('genre', mysql.VARCHAR(length=50), nullable=False),
                    sa.Column('current', mysql.SMALLINT(), autoincrement=False, nullable=True),
                    sa.Column('album', mysql.VARCHAR(length=150), nullable=True),
                    sa.Column('release', mysql.VARCHAR(length=4), nullable=True),
                    sa.Column('played', mysql.SMALLINT(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='utf8mb3',
                    mysql_engine='InnoDB'
                    )
    with op.batch_alter_table('songfull', schema=None) as batch_op:
        batch_op.create_index('ix_songfull_genre', ['genre'], unique=False)

    op.create_table('past_game',
                    sa.Column('user_id_or_session', mysql.VARCHAR(length=100), nullable=False),
                    sa.Column('date', sa.DATE(), nullable=False),
                    sa.Column('attempts_made_general', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('attempts_made_rock', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('attempts_made_hiphop', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('correct_guess_general', mysql.TINYINT(display_width=1), autoincrement=False,
                              nullable=True),
                    sa.Column('correct_guess_rock', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
                    sa.Column('correct_guess_hiphop', mysql.TINYINT(display_width=1), autoincrement=False,
                              nullable=True),
                    sa.Column('archive_date', sa.DATE(), nullable=False),
                    sa.ForeignKeyConstraint(['archive_date'], ['archive.date_played'], name='past_game_ibfk_1'),
                    sa.PrimaryKeyConstraint('user_id_or_session', 'date'),
                    mysql_default_charset='utf8mb3',
                    mysql_engine='InnoDB'
                    )
    with op.batch_alter_table('past_game', schema=None) as batch_op:
        batch_op.create_index('ix_past_game_date', ['date'], unique=False)

    op.create_table('current_game',
                    sa.Column('user_id_or_session', mysql.VARCHAR(length=100), nullable=False),
                    sa.Column('current_genre', mysql.VARCHAR(length=50), nullable=True),
                    sa.Column('guesses_left', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('date', sa.DATE(), nullable=False),
                    sa.Column('archive_date', sa.DATE(), nullable=False),
                    sa.ForeignKeyConstraint(['archive_date'], ['archive.date_played'], name='current_game_ibfk_1'),
                    sa.PrimaryKeyConstraint('user_id_or_session'),
                    mysql_default_charset='utf8mb3',
                    mysql_engine='InnoDB'
                    )
    op.create_table('archive',
                    sa.Column('date_played', sa.DATE(), nullable=False),
                    sa.Column('general_track', mysql.VARCHAR(length=150), nullable=True),
                    sa.Column('rock_track', mysql.VARCHAR(length=150), nullable=True),
                    sa.Column('hiphop_track', mysql.VARCHAR(length=150), nullable=True),
                    sa.ForeignKeyConstraint(['general_track'], ['songfull.id'], name='archive_ibfk_1'),
                    sa.ForeignKeyConstraint(['hiphop_track'], ['songfull.id'], name='archive_ibfk_3'),
                    sa.ForeignKeyConstraint(['rock_track'], ['songfull.id'], name='archive_ibfk_2'),
                    sa.PrimaryKeyConstraint('date_played'),
                    mysql_default_charset='utf8mb3',
                    mysql_engine='InnoDB'
                    )
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.create_index('ix_archive_date_played', ['date_played'], unique=False)

    # ### end Alembic commands ###
