"""changes again

Revision ID: f68687f31f74
Revises: e4d77ad691b1
Create Date: 2023-10-24 19:38:20.744931

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f68687f31f74'
down_revision = 'e4d77ad691b1'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_constraint(table_name='archive', constraint_name='archive_ibfk_4', type_='foreignkey')
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_column('past_game_date')

    with op.batch_alter_table('past_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive_date', sa.Date(), nullable=False))
        batch_op.create_foreign_key(None, 'archive', ['archive_date'], ['date_played'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('archive_date')

    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past_game_date', sa.DATE(), nullable=True))
        batch_op.create_foreign_key('archive_ibfk_4', 'past_game', ['past_game_date'], ['date'])

    # ### end Alembic commands ###
